# Spring config
spring:
  # Spring data config
  data:
    # Mongo DB config
    mongodb:
      # database connection string
      uri: mongodb+srv://jvdw20152022:hIQJm7EOpt68vqbq@cluster0.phxhq.mongodb.net/cst339?retryWrites=true&w=majority
      database: ProductAppTest
# Spring Doc is used to automatically generate Swagger OAS 3 documentation
springdoc:
  # set the default media type
  default-produces-media-type: application/json